### PR TITLE
fix: compile the iOS bridge with Objective-C exceptions enabled

### PR DESCRIPTION
**Pull request by bobbyg603**
## The bug

Every iOS build fails:

```
Libraries/com.bugsplat.unity/Editor/IOS/ObjC/BugSplatBridge.mm:46:2
Cannot use '@try' with Objective-C exceptions disabled
```

`ReadLogTail` guards its `NSFileHandle` seek/read with `@try` — those calls raise `NSFileHandleOperationException` on I/O failure — and Unity's `UnityFramework` target compiles with `GCC_ENABLE_OBJC_EXCEPTIONS = NO`.

Introduced in #225, which rewrote the bridge and added the guard. It has been broken for every iOS build since; the macOS bridge is unaffected because Unity compiles it separately.

## Reproduced

Against the real iOS SDK and the vendored xcframework:

```
$ xcrun --sdk iphoneos clang++ -fsyntax-only -x objective-c++ -target arm64-apple-ios13.0 \
    -FEditor/IOS/Frameworks/BugSplat.xcframework/ios-arm64 \
    -fno-objc-exceptions Editor/IOS/ObjC/BugSplatBridge.mm
BugSplatBridge.mm:46:2: error: cannot use '@try' with Objective-C exceptions disabled

$ ... -fobjc-exceptions ...
(clean)
```

Same file, same line as the Xcode error.

## The fix

**`BugSplatBridge.mm.meta`** — the plugin importer's iOS `CompileFlags` now carries `-fobjc-exceptions`. This is the targeted fix: one compiler flag on one file, no project-wide change.

**`Editor/PostBuild.cs`** — the Xcode post-process also sets `GCC_ENABLE_OBJC_EXCEPTIONS = YES` on `UnityFramework`. A project that already imported this plugin keeps its cached importer settings, so the `.meta` change alone would not reach it; without this those projects stay broken after upgrading. Enabling the capability does not change behavior for code that never throws.

Keeping the `@try` rather than removing it: it exists so an unreadable log file degrades to "no attachment" instead of taking down the crash reporter's own delegate.

## Verification

- Compiles clean with `-fobjc-exceptions` and fails identically to the reported error with `-fno-objc-exceptions`, against the iOS SDK.
- `PostBuild.cs` has no syntax errors (Roslyn `csc -langversion:latest`; note `mcs` cannot parse this file at all — it rejects the C# 8 switch expression at line 42, unmodified).
- [x] A real iOS build from Unity, which is the only way to confirm the importer flag reaches the generated project.

`PostBuild.cs` is CRLF; the diff is 6 added lines only.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_011bapaeRsoZPuK3jjtdk51V

### CODE REVIEW

**Review by daveplunkett — APPROVED** [review]

File: CHANGELOG.md [hunk 1]
```diff
@@ -66,6 +66,7 @@ Upgrading from 4.x? See [Migrating from 4.x](Documentation~/migrating-from-4x.md
 
 ### Fixed
 
+- iOS builds failed to compile with `Cannot use '@try' with Objective-C exceptions disabled`. `BugSplatBridge.mm` guards its `NSFileHandle` reads with `@try`, and Unity's `UnityFramework` target sets `GCC_ENABLE_OBJC_EXCEPTIONS = NO`. The plugin importer now passes `-fobjc-exceptions` for that file, and the Xcode post-process sets the target property as well, for projects that imported the plugin before the importer setting existed.
```
[the remark this answers is not in the document]
Comment (bobbyg603) [reply CHANGELOG.md]: **Fixed** in 9c99bd3. The entry now says the post-process sets the same flag on the file in the generated project, and that it falls back to `GCC_ENABLE_OBJC_EXCEPTIONS` on the whole `UnityFramework` target only when the file cannot be found there.

The wording described the first version of this branch, which did set the target property outright; 04e5566 narrowed it to the file and the changelog was not updated with it.

File: Editor/PostBuild.cs [hunk 2]
```diff
@@ -438,6 +440,40 @@ private static void DisableUnityCrashReporter(string pathToBuiltProject)
...
 		}
 
+		/// <summary>
+		/// BugSplatBridge.mm guards its NSFileHandle reads with @try, and Unity compiles UnityFramework
+		/// with GCC_ENABLE_OBJC_EXCEPTIONS = NO. The plugin importer carries -fobjc-exceptions for the
+		/// file, but a project that imported the plugin before that setting existed can still be building
+		/// with the old flags, so it is set on the file here as well.
+		///
+		/// Per file rather than per target: Unity disables Objective-C exceptions for the whole framework
+		/// deliberately, and one bridge needing them is no reason to change how Unity's own code compiles.
```
[the remark this answers is not in the document]
Comment (bobbyg603) [reply Editor/PostBuild.cs:450]: **Fixed** in 9c99bd3. The summary now names the fallback: a project where the file cannot be located gets the target property instead, which is wider than wanted but better than an iOS build that does not compile.

Same cause as the changelog thread — the comment was written for the target-wide version and kept its 'per file rather than per target' framing after 04e5566 made the fallback possible.
